/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'courseId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getCourseById' : IDL.Func([IDL.Nat], [Course], ['query']),
  'initializeCourses' : IDL.Func([], [], []),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'courseId' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getCourseById' : IDL.Func([IDL.Nat], [Course], ['query']),
    'initializeCourses' : IDL.Func([], [], []),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };